version: "3.4"

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    working_dir: /code
    volumes:
      - ./:/code
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
  php:
    #image: php:8-fpm
    working_dir: /code
    build:
      context: .
      dockerfile: php.docker
    volumes:
      - ./:/code